name             'etc'
maintainer       'Wimdu'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs/Configures etc'
long_description ''
version          '0.1.0'
