name             'root'
maintainer       'Frank Woeckener'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Configures the root/vagrant user with ssh'
long_description ''
version          '0.1.0'
depends          'etc'
