name             'sipp'
maintainer       'Wimdu'
maintainer_email 'frank.woeckener@wimdu.com'
license          'All rights reserved'
description      'Installs the sipp package'
long_description ''
version          '0.1.0'
depends          'etc'
