name             'wim-user'
maintainer       'Frank Woeckener'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs/Configures the main Voice user'
long_description ''
version          '0.1.0'
depends          'etc'
