name             'mongodb'
maintainer       'Frank Woeckener'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs the mongodb packages'
long_description ''
version          '0.1.0'
depends          'etc'
