name             'voice-ahn'
maintainer       'Wimdu'
maintainer_email 'frank.woeckener@wimdu.com'
license          'All rights reserved'
description      'Installs/Configures the adhearsion project'
long_description ''
version          '0.1.0'
depends          'etc'
