name             'voice-rails'
maintainer       'Frank Woeckener'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs/Configures the rails project'
long_description ''
version          '0.1.0'
depends          'etc'
