name             'voice-numbers'
maintainer       'Frank Woeckener'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs/Configures the statistics daemon'
long_description ''
version          '0.1.0'
depends          'etc'
