name             'rabbitmq'
maintainer       'Frank Woeckener'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs the rabbitmq packages'
long_description ''
version          '0.1.0'
depends          'etc'
