name             'vim'
maintainer       'Wimdu'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs/Configures the vim package'
long_description ''
version          '0.1.0'
depends          'etc'
