name             'wim-user-dev'
maintainer       'Wimdu'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Adds some development tools'
long_description ''
version          '0.1.0'
depends          'etc'
