name             'postfix'
maintainer       'Wimdu'
maintainer_email 'frank.woeckener@wimdu.com'
license          'All rights reserved'
description      'Configures the postfix mail server'
long_description ''
version          '0.1.0'
depends          'etc'
