name             'aptget'
maintainer       'Wimdu'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs/updates basic dpkg packages'
long_description ''
version          '0.1.0'
depends          'etc'
