name             'mysql'
maintainer       'Wimdu'
maintainer_email 'frank.woeckener@wimdu.com'
license          'All rights reserved'
description      'Configures the mysql database with asterisk schema'
long_description ''
version          '0.1.0'
depends          'etc'
