name             'mysql'
maintainer       'Frank Woeckener'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Configures the mysql database with asterisk schema'
long_description ''
version          '0.1.0'
depends          'etc'
