name             'v4l2'
maintainer       'Wimdu'
maintainer_email 'frank.woeckener@wimdu.com'
license          'All rights reserved'
description      'Installs the v4l2-loopback device'
long_description ''
version          '0.1.0'
depends          'etc'
