name             'voice-specs'
maintainer       'Wimdu'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs the load testing repo'
long_description ''
version          '0.1.0'
depends          'etc'
