name             'mri'
maintainer       'Frank Woeckener'
maintainer_email 'fwoeck@gmail.com'
license          'All rights reserved'
description      'Installs mri ruby with rvm'
long_description ''
version          '0.1.0'
depends          'etc'
